# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb44778e2da6f51d7feac6e0838e4a967f82ac193293904eadd10eb93630bb03df016ba01c2ec1a4a538e7a5aaf94c7ad24faa797e363a37c0103915e0abee9e

test:
  secret_key_base: 8bfab4f89a597223e234667fc85076fda34be31b10ffd141ff245338de76acc595e3d69cf04f8ca157ebe32e9b9e5af33147a7021d7902f5690488633f2f27d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
